version: '3.9'
services:
  spark:
    image: 'docker.io/bitnami/spark:3.1.2'
    volumes:
      - ./data:/opt/data
      - ./driver/postgresql-42.2.24.jar:/opt/bitnami/spark/jars/postgresql-42.2.24.jar
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_CLASSPATH=/opt/bitnami/spark/jars
    ports:
      - '7077:7077'
      - '18080:8080'
  spark-worker-1:
    image: docker.io/bitnami/spark:3
    volumes:
      - ./data:/opt/data
      - ./driver/postgresql-42.2.24.jar:/opt/bitnami/spark/jars/postgresql-42.2.24.jar
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_CLASSPATH=/opt/bitnami/spark/jars
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=warehouse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  etl:
    build:
      context: .
      target: etl
    volumes:
      - ./data:/opt/data
      - ./main.py:/opt/main.py
      - ./db_properties.ini:/opt/db_properties.ini
      - ./driver/postgresql-42.2.24.jar:/opt/bitnami/spark/jars/postgresql-42.2.24.jar