CREATE USER root;
CREATE DATABASE warehouse;
GRANT ALL PRIVILEGES ON DATABASE warehouse TO root;
REVOKE ALL ON DATABASE warehouse FROM root;
GRANT CONNECT ON DATABASE warehouse TO root;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO root;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO root;
ALTER USER root WITH SUPERUSER;

CREATE USER spark;
CREATE DATABASE warehouse;
GRANT ALL PRIVILEGES ON DATABASE warehouse TO spark;
REVOKE ALL ON DATABASE warehouse FROM spark;
GRANT CONNECT ON DATABASE warehouse TO spark;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO spark;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO spark;
ALTER USER spark WITH SUPERUSER;